// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: buildrequest.proto

package buildrequest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GitUrl        string                 `protobuf:"bytes,1,opt,name=gitUrl,proto3" json:"gitUrl,omitempty"`
	GitBranch     string                 `protobuf:"bytes,2,opt,name=gitBranch,proto3" json:"gitBranch,omitempty"`
	CurrentUser   string                 `protobuf:"bytes,3,opt,name=currentUser,proto3" json:"currentUser,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=Owner,proto3" json:"Owner,omitempty"`
	PublicRepo    bool                   `protobuf:"varint,5,opt,name=publicRepo,proto3" json:"publicRepo,omitempty"`
	AppFrameWork  string                 `protobuf:"bytes,6,opt,name=AppFrameWork,proto3" json:"AppFrameWork,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBuildRequest) Reset() {
	*x = CreateBuildRequest{}
	mi := &file_buildrequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuildRequest) ProtoMessage() {}

func (x *CreateBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buildrequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuildRequest.ProtoReflect.Descriptor instead.
func (*CreateBuildRequest) Descriptor() ([]byte, []int) {
	return file_buildrequest_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBuildRequest) GetGitUrl() string {
	if x != nil {
		return x.GitUrl
	}
	return ""
}

func (x *CreateBuildRequest) GetGitBranch() string {
	if x != nil {
		return x.GitBranch
	}
	return ""
}

func (x *CreateBuildRequest) GetCurrentUser() string {
	if x != nil {
		return x.CurrentUser
	}
	return ""
}

func (x *CreateBuildRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CreateBuildRequest) GetPublicRepo() bool {
	if x != nil {
		return x.PublicRepo
	}
	return false
}

func (x *CreateBuildRequest) GetAppFrameWork() string {
	if x != nil {
		return x.AppFrameWork
	}
	return ""
}

type CreateBuildRespone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBuildRespone) Reset() {
	*x = CreateBuildRespone{}
	mi := &file_buildrequest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuildRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuildRespone) ProtoMessage() {}

func (x *CreateBuildRespone) ProtoReflect() protoreflect.Message {
	mi := &file_buildrequest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuildRespone.ProtoReflect.Descriptor instead.
func (*CreateBuildRespone) Descriptor() ([]byte, []int) {
	return file_buildrequest_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBuildRespone) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_buildrequest_proto protoreflect.FileDescriptor

var file_buildrequest_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc6, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x67,
	0x69, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x69, 0x74,
	0x55, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x69, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x69, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x63,
	0x68, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x52, 0x65, 0x70, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x52, 0x65, 0x70, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x70, 0x70,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x41, 0x70, 0x70, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x22, 0x2c, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x5d, 0x0a, 0x13, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x46, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x13,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x61, 0x70, 0x70, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_buildrequest_proto_rawDescOnce sync.Once
	file_buildrequest_proto_rawDescData = file_buildrequest_proto_rawDesc
)

func file_buildrequest_proto_rawDescGZIP() []byte {
	file_buildrequest_proto_rawDescOnce.Do(func() {
		file_buildrequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_buildrequest_proto_rawDescData)
	})
	return file_buildrequest_proto_rawDescData
}

var file_buildrequest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_buildrequest_proto_goTypes = []any{
	(*CreateBuildRequest)(nil), // 0: CreateBuildRequest
	(*CreateBuildRespone)(nil), // 1: CreateBuildRespone
}
var file_buildrequest_proto_depIdxs = []int32{
	0, // 0: BuildRequestService.CreateBuildRequestMethod:input_type -> CreateBuildRequest
	1, // 1: BuildRequestService.CreateBuildRequestMethod:output_type -> CreateBuildRespone
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_buildrequest_proto_init() }
func file_buildrequest_proto_init() {
	if File_buildrequest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_buildrequest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_buildrequest_proto_goTypes,
		DependencyIndexes: file_buildrequest_proto_depIdxs,
		MessageInfos:      file_buildrequest_proto_msgTypes,
	}.Build()
	File_buildrequest_proto = out.File
	file_buildrequest_proto_rawDesc = nil
	file_buildrequest_proto_goTypes = nil
	file_buildrequest_proto_depIdxs = nil
}
